apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: drcylau.ddns.net-com-tls
spec:
  secretName: drcylau.ddns.net-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: drcylau.ddns.net
  dnsNames:
    - drcylau.ddns.net
